bug fix

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -25,7 +25,9 @@ jobs:
         run: npm install
 
       - name: Build project
-        run: npm run build
+        run: |
+              npm run build
+              echo $? # Logs the exit code
 
       - name: Deploy to GitHub Pages
         uses: peaceiris/actions-gh-pages@v3
